In [ ]:
# !sudo apt-get install -y fonts-nanum
# !sudo fc-cache -fv
# !rm ~/.cache/matplotlib -rf

In [8]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier

In [4]:
iris_df = load_iris()
X = iris_df.data
target = iris_df.target

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size= 0.3, random_state=20)
pd.DataFrame(X_train).head()

0    1    2    3
0  4.7  3.2  1.3  0.2
1  5.4  3.9  1.7  0.4
2  5.0  3.3  1.4  0.2
3  5.7  2.5  5.0  2.0
4  5.1  3.8  1.9  0.4

In [15]:
model = KNeighborsClassifier()
model.fit(X_train, y_train)
model.score(X_train,y_train)

0.9809523809523809

In [16]:
x_pred = np.array([[5,3.2,5.1,1.8]])
y_pred = model.predict(x_pred)
iris_df['target_names'][y_pred]

array(['virginica'], dtype='<U10')

In [22]:
y_pred = model.predict(X_test)
for i in range(len(y_pred)):
  y_pred2 = y_pred[i]
  print(f'{X_test[i]}:{iris_df["target_names"][y_pred2]}')

model.score(X_test, y_test)

[4.6 3.2 1.4 0.2]:setosa
[6.1 2.8 4.7 1.2]:versicolor
[6.4 2.9 4.3 1.3]:versicolor
[7.2 3.  5.8 1.6]:virginica
[5.8 2.7 4.1 1. ]:versicolor
[5.5 2.5 4.  1.3]:versicolor
[6.8 3.2 5.9 2.3]:virginica
[5.1 3.7 1.5 0.4]:setosa
[6.7 2.5 5.8 1.8]:virginica
[4.8 3.  1.4 0.1]:setosa
[6.5 3.  5.2 2. ]:virginica
[6.8 2.8 4.8 1.4]:versicolor
[6.  2.2 5.  1.5]:virginica
[5.  3.2 1.2 0.2]:setosa
[5.2 3.4 1.4 0.2]:setosa
[7.7 2.8 6.7 2. ]:virginica
[4.3 3.  1.1 0.1]:setosa
[6.6 2.9 4.6 1.3]:versicolor
[5.8 2.8 5.1 2.4]:virginica
[4.9 2.4 3.3 1. ]:versicolor
[7.  3.2 4.7 1.4]:versicolor
[5.9 3.  5.1 1.8]:virginica
[6.4 2.7 5.3 1.9]:virginica
[5.4 3.4 1.7 0.2]:setosa
[6.3 2.5 4.9 1.5]:virginica
[5.5 2.4 3.7 1. ]:versicolor
[5.1 2.5 3.  1.1]:versicolor
[4.9 3.1 1.5 0.2]:setosa
[6.5 3.  5.8 2.2]:virginica
[6.3 2.8 5.1 1.5]:virginica
[5.7 3.  4.2 1.2]:versicolor
[5.6 3.  4.1 1.3]:versicolor
[5.1 3.5 1.4 0.2]:setosa
[5.1 3.8 1.6 0.2]:setosa
[4.8 3.4 1.6 0.2]:setosa
[4.9 2.5 4.5 1.7]:versicolor
[6.  3.4 4.5

0.9555555555555556