In [15]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib as mpl
import seaborn as sns
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.neighbors import KNeighborsClassifier

In [2]:
iris_df = load_iris()
X = iris_df.data
target = iris_df.target

In [3]:
X_train, X_test, y_train, y_test = train_test_split(X, target, test_size= 0.3, random_state=20)
pd.DataFrame(X_train).head()

0    1    2    3
0  4.7  3.2  1.3  0.2
1  5.4  3.9  1.7  0.4
2  5.0  3.3  1.4  0.2
3  5.7  2.5  5.0  2.0
4  5.1  3.8  1.9  0.4

## KNeighborsClassifier

In [ ]:
# k 값 구하기 위한 최적화
# for k in range(1,30):
#   knn = KNeighborsClassifier(n_neighbors=k)
#   knn.fit(X_train,y_train)
#   pred = knn.predict(X_test)
#   print(k, (pd.Series(pred)==y_test).mean())

In [19]:
# 교차 검증 추가 / 과적합 방지
for k in range(1,30):
  knn = KNeighborsClassifier(n_neighbors=k)
  scores = cross_val_score(knn, X_train, y_train, cv=5)
  print(f'{k}:{np.mean(scores)}')

1:0.9714285714285715
2:0.9428571428571428
3:0.9619047619047618
4:0.9428571428571428
5:0.9428571428571428
6:0.9428571428571428
7:0.9333333333333333
8:0.9333333333333333
9:0.9523809523809523
10:0.9428571428571428
11:0.9428571428571428
12:0.9333333333333333
13:0.9523809523809523
14:0.9333333333333333
15:0.9428571428571428
16:0.9142857142857144
17:0.9238095238095239
18:0.9428571428571428
19:0.9238095238095239
20:0.9428571428571428
21:0.9428571428571428
22:0.9142857142857144
23:0.9238095238095239
24:0.9333333333333333
25:0.9142857142857143
26:0.9142857142857143
27:0.9238095238095237
28:0.9238095238095237
29:0.9238095238095237


In [12]:
model = KNeighborsClassifier(n_neighbors=5)
model.fit(X_train, y_train)
model.score(X_train,y_train)

0.9809523809523809

In [13]:
x_pred = np.array([[5,3.2,5.1,1.8]])
y_pred = model.predict(x_pred)
iris_df['target_names'][y_pred]

array(['virginica'], dtype='<U10')

In [14]:
y_pred = model.predict(X_test)
for i in range(len(y_pred)):
  y_pred2 = y_pred[i]
  print(f'{X_test[i]}:{iris_df["target_names"][y_pred2]}')

model.score(X_test, y_test)

[4.6 3.2 1.4 0.2]:setosa
[6.1 2.8 4.7 1.2]:versicolor
[6.4 2.9 4.3 1.3]:versicolor
[7.2 3.  5.8 1.6]:virginica
[5.8 2.7 4.1 1. ]:versicolor
[5.5 2.5 4.  1.3]:versicolor
[6.8 3.2 5.9 2.3]:virginica
[5.1 3.7 1.5 0.4]:setosa
[6.7 2.5 5.8 1.8]:virginica
[4.8 3.  1.4 0.1]:setosa
[6.5 3.  5.2 2. ]:virginica
[6.8 2.8 4.8 1.4]:versicolor
[6.  2.2 5.  1.5]:virginica
[5.  3.2 1.2 0.2]:setosa
[5.2 3.4 1.4 0.2]:setosa
[7.7 2.8 6.7 2. ]:virginica
[4.3 3.  1.1 0.1]:setosa
[6.6 2.9 4.6 1.3]:versicolor
[5.8 2.8 5.1 2.4]:virginica
[4.9 2.4 3.3 1. ]:versicolor
[7.  3.2 4.7 1.4]:versicolor
[5.9 3.  5.1 1.8]:virginica
[6.4 2.7 5.3 1.9]:virginica
[5.4 3.4 1.7 0.2]:setosa
[6.3 2.5 4.9 1.5]:virginica
[5.5 2.4 3.7 1. ]:versicolor
[5.1 2.5 3.  1.1]:versicolor
[4.9 3.1 1.5 0.2]:setosa
[6.5 3.  5.8 2.2]:virginica
[6.3 2.8 5.1 1.5]:virginica
[5.7 3.  4.2 1.2]:versicolor
[5.6 3.  4.1 1.3]:versicolor
[5.1 3.5 1.4 0.2]:setosa
[5.1 3.8 1.6 0.2]:setosa
[4.8 3.4 1.6 0.2]:setosa
[4.9 2.5 4.5 1.7]:versicolor
[6.  3.4 4.5

0.9555555555555556

In [10]:
y_pred

array([0, 1, 1, 2, 1, 1, 2, 0, 2, 0, 2, 1, 2, 0, 0, 2, 0, 1, 2, 1, 1, 2,
       2, 0, 2, 1, 1, 0, 2, 2, 1, 1, 0, 0, 0, 1, 1, 0, 1, 2, 1, 2, 0, 1,
       1])

In [20]:
from sklearn.impute import KNNImputer

In [50]:
tit_df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/kaggle_train.csv')
tit_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [51]:
tit_df = tit_df.drop(['PassengerId','Name','Ticket','Cabin'],axis=1)
# cat_var = tit_df[['Sex','Embarked']]
# cat_enc = pd.get_dummies(cat_var, drop_first=True)

In [44]:
# tit_df = tit_df.drop(['Sex','Embarked'],axis =1)
# tit_df = pd.concat([tit_df, cat_enc], axis=1)


In [52]:
tit_df.Sex = tit_df.Sex.map({'male':1,'female':0})
tit_df['Age_fill'] = tit_df.groupby(['Pclass', 'Sex'])['Age'].apply(lambda x: x.fillna(x.mean()))
tit_df.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 9 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Survived  891 non-null    int64  
 1   Pclass    891 non-null    int64  
 2   Sex       891 non-null    int64  
 3   Age       714 non-null    float64
 4   SibSp     891 non-null    int64  
 5   Parch     891 non-null    int64  
 6   Fare      891 non-null    float64
 7   Embarked  889 non-null    object 
 8   Age_fill  891 non-null    float64
dtypes: float64(3), int64(5), object(1)
memory usage: 62.8+ KB


In [48]:
from sklearn.preprocessing import StandardScaler




# imp = KNNImputer(n_neighbors=5)
# tit_df = imp.fit_transform(tit_df)

# pd.DataFrame(tit_df).isna().sum()
# pd.DataFrame(tit_df)

ValueError: ignored