In [ ]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets, metrics
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.metrics import accuracy_score, roc_auc_score, confusion_matrix, classification_report
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler

In [ ]:
iris = datasets.load_iris()
X = iris.data
y = iris.target

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3)

In [ ]:
sc = StandardScaler()
X_train_sc = sc.fit_transform(X_train)
X_test_sc = sc.transform(X_test)

In [ ]:
params_boost ={
    # "loss":["deviance"],
    "learning_rate": [0.01, 0.025, 0.05, 0.075, 0.1, 0.15, 0.2],
    # "min_samples_split": np.linspace(0.1, 0.5, 12),
    # "min_samples_leaf": np.linspace(0.1, 0.5, 12),
    "max_depth":[3,5,8],
    # "max_features":["log2","sqrt"],
    # "criterion": ["friedman_mse",  "mae"],
    "subsample":[0.5, 0.618, 0.8, 0.85, 0.9, 0.95, 1.0],
    "n_estimators":[10]
}
model = GradientBoostingClassifier(random_state=20)
# verbose=2 (진행과정을 세세하게 보여줌)
gboost_cv = GridSearchCV(model, param_grid = params_boost,cv=3, verbose=2)
gboost_cv.fit(X_train_sc, y_train)
print(gboost_cv.best_params_)
print(gboost_cv.best_score_)

Fitting 3 folds for each of 147 candidates, totalling 441 fits
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.5; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.618; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.618; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.618; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.8; total time=   0.1s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.8; total time=   0.2s
[CV] END learning_rate=0.01, max_depth=3, n_estimators=10, subsample=0.85; total time=   0.1s


In [ ]:
# model = GradientBoostingClassifier(max_depth=2,
#                                    learning_rate=0.01,
#                                    random_state=20)

model = gboost_cv.best_estimator_
y_pred = model.predict(X_test_sc)
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

0.9333333333333333
[[ 9  0  0]
 [ 0 15  2]
 [ 0  1 18]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         9
           1       0.94      0.88      0.91        17
           2       0.90      0.95      0.92        19

    accuracy                           0.93        45
   macro avg       0.95      0.94      0.94        45
weighted avg       0.93      0.93      0.93        45

