In [1]:
import numpy as np

## numpy: 과학 계산을 위한 lib
### matrix/vector 연산 // python list 보다 처리 속도가 빠름

In [32]:
def numpy1_f():
    a = [[1,2,3],[4,5,6]]
    print(a)
    print(type(a))
    # 리스트를 배열로 바꿈
    b = np.array(a)
    print(b)    
    print(type(b))
    
    print(f'a[0][0]:{a[0][0]}')
    print(f'a[1][1]:{a[1][1]}')
    
    print('배열의 차원:', b.ndim)
    print('배열의 크기:', b.shape)
#     b= b.reshape(3,2)
#     print(b)    

    # ex) 2배하기 : 파이썬 일반적 방법
    data = [1,2,3,4,5]
    res = []
    for n in data:
        res.append(n*2)
    print(res)
    print(data*2)
    
    # numpy 벡터화 연산
    x = np.array(data)
    print(x *2)
    print(x[-1])

In [38]:
def numpy2_f():
    data = [[1,2,3],[4,5,6]]
    nd = np.array(data)
    # 3개 모두 같은 방법
    for i, j, k in nd:
        print(i,j,k)
        
    print('='*20)
    for i in nd:
        for j in i:
            print(j, end='\t')
        print()
    print('='*20)
    for i in range(len(nd)):
        for j in range(len(nd[i])):
            print(nd[i][j], end='\t')
        print()

In [46]:
def numpy3_f():
    data = [[0,1,2,3],[4,5,6,7]]
    a = np.array(data)
    # 첫번째 행 전체
    print(a[0,:])
    # 첫번째 열 전체
    print(a[:,0])
    # 2번째 행, 2번째 열부터 끝까지
    print(a[1][1:])

In [190]:
def numpy4_f():
    data = [[0,1,2,3],
           [4,5,6,7],
           [8,9,10,11],
           [12,13,14,15]]
    a= np.array(data)
    #a[시작: 끝: 증가치]
    print(a[::2])
    print(a[:2:])
    
    # 1) 모든 행에서 1,3 열만 추출
    print('1번')
    print(a[:,::2])

    # 2) 1,3행의 2번째 열~3번째 열
    print('2번')
    print(a[::2, 1:3])
    
    data2 = [[0,1,2,3,4],
             [5,6,7,8,9],
             [10,11,12,13,14]]
    b = np.array(data2)
    # 3) 7 indexing
    print('3번')
    print(b[1][2])
    # 4) 14 indexing
    print('4번')
    print(b[2][-1])
    # 5) [6,7] slicing
    print('5번')
    print(b[1,1:3])
    # 6) [7,12] slicing
    print('6번')
    print(b[1:3,2])
    print('배열의 차원:', b[1:3,2].ndim)
    print('배열의 크기:', b[1:3,2].shape)
    
    # 7) [[7],[12]] slicing
    print('7번')
    print(b[1:3,2:3])
    print('배열의 차원:', b[1:3,2:3].ndim)
    print('배열의 크기:', b[1:3,2:3].shape)
    
    # 8) [[3,4],[8,9]] slicing
    print('8번')
    print(b[0:2,3:5])
    print('배열의 차원:', b[0:2,3:5].ndim)
    print('배열의 크기:', b[0:2,3:5].shape)
    


In [191]:
if __name__ == '__main__':
#     numpy1_f()
#     numpy2_f()
#     numpy3_f()
    numpy4_f()

[[ 0  1  2  3]
 [ 8  9 10 11]]
[[0 1 2 3]
 [4 5 6 7]]
1번
[[ 0  2]
 [ 4  6]
 [ 8 10]
 [12 14]]
2번
[[ 1  2]
 [ 9 10]]
3번
7
4번
14
5번
[6 7]
6번
[ 7 12]
배열의 차원: 1
배열의 크기: (2,)
7번
[[ 7]
 [12]]
배열의 차원: 2
배열의 크기: (2, 1)
8번
[[3 4]
 [8 9]]
배열의 차원: 2
배열의 크기: (2, 2)
